In [17]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split


housing =fetch_california_housing()
X_train , X_test , y_train,y_test = train_test_split(housing.data ,housing.target, random_state = 42)

In [18]:
import tensorflow as tf
tf.random.set_seed(42)
normalization_layer = tf.keras.layers.Normalization()
hidden_layer1 = tf.keras.layers.Dense(30, activation="relu")
hidden_layer2 = tf.keras.layers.Dense(30, activation="relu")
concat_layer = tf.keras.layers.Concatenate()
output_layer = tf.keras.layers.Dense(1)

In [19]:
input_ = tf.keras.layers.Input(shape=X_train.shape[1:])
normalized = normalization_layer(input_)
hidden_1 = hidden_layer1(normalized)
hidden_2 = hidden_layer2(hidden_1)
concat = concat_layer([normalized, hidden_2])
outputs = output_layer(concat)
model = tf.keras.Model(inputs=input_, outputs=outputs)
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_1       │ (None, 8)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ normalization_1     │ (None, 8)         │         17 │ input_layer_1[0]… │
│ (Normalization)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 30)        │        270 │ normalization_1[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 30)        │        930 │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_1       │ (None, 38)        │          0 │ normalization_1[… │
│ (Concatenate)       │                   │            │ dense_4[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 1)         │         39 │ concatenate_1[0]… │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 1,256 (4.91 KB)

 Trainable params: 1,239 (4.84 KB)

 Non-trainable params: 17 (72.00 B)

In [20]:
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
model.compile(loss="mse",
              optimizer=optimizer,
              metrics=["RootMeanSquaredError"])

In [21]:
normalization_layer.adapt(X_train)
history = model.fit(X_train, y_train,validation_split=0.2,epochs=250)

Epoch 1/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 467us/step - RootMeanSquaredError: 1.1489 - loss: 1.3200 - val_RootMeanSquaredError: 0.7345 - val_loss: 0.5395
Epoch 2/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 295us/step - RootMeanSquaredError: 0.6762 - loss: 0.4572 - val_RootMeanSquaredError: 0.6678 - val_loss: 0.4459
Epoch 3/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 298us/step - RootMeanSquaredError: 0.6325 - loss: 0.4001 - val_RootMeanSquaredError: 0.6481 - val_loss: 0.4200
Epoch 4/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - RootMeanSquaredError: 0.6148 - loss: 0.3780 - val_RootMeanSquaredError: 0.6363 - val_loss: 0.4049
Epoch 5/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 332us/step - RootMeanSquaredError: 0.6053 - loss: 0.3663 - val_RootMeanSquaredError: 0.6277 - val_loss: 0.3940
Epoch 6/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 339us/step - RootMeanSquaredError: 0.5984 - loss: 0.3580 - val_RootMeanSquaredError: 0.6203 - val_loss: 0.3848
Epoch 7/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - RootMeanSquaredError: 0.5923 - loss: 0.3509 - val_RootMeanSquaredError: 0.6136 - val_loss: 0.3765
Epoch 8/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 340us/step - RootMeanSquaredError: 0.5861 - loss: 0.3435 - val_RootMeanSquaredError: 0.6062 - val_loss: 0.3674
Epoch 9/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 336us/step - RootMeanSquaredError: 0.5798 - loss: 0.3362 - val_RootMeanSquaredError: 0.6001 - val_loss: 0.3601
Epoch 10/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 327us/step - RootMeanSquaredError: 0.5711 - loss: 0.3262 - val_RootMeanSquaredError: 0.5923 - val_loss: 0.3508
Epoch 11/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - RootMeanSquaredError: 0.5662 - loss: 0.3206 - val_RootMeanSquaredError: 0.5865 - val_loss: 0.3440
Epoch 12/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 331us/step - RootMeanSquaredError: 0.5603 - loss: 0.3140 - val_RootMeanSquaredError: 0.5813 - val_loss: 0.3379
Epoch 13/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - RootMeanSquaredError: 0.5559 - loss: 0.3090 - val_RootMeanSquaredError: 0.5775 - val_loss: 0.3335
Epoch 14/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - RootMeanSquaredError: 0.5531 - loss: 0.3059 - val_RootMeanSquaredError: 0.5763 - val_loss: 0.3322
Epoch 15/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 325us/step - RootMeanSquaredError: 0.5487 - loss: 0.3011 - val_RootMeanSquaredError: 0.5722 - val_loss: 0.3274
Epoch 16/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - RootMeanSquaredError: 0.5441 - loss: 0.2961 - val_RootMeanSquaredError: 0.5676 - val_loss: 0.3222
Epoch 17/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 323us/step - RootMeanSquaredError: 0.5416 - loss: 0.2934 - val_RootMeanSquaredError: 0.5641 - val_loss: 0.3182
Epoch 18/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 326us/step - RootMeanSquaredError: 0.5407 - loss: 0.2924 - val_RootMeanSquaredError: 0.5630 - val_loss: 0.3169
Epoch 19/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 325us/step - RootMeanSquaredError: 0.5362 - loss: 0.2875 - val_RootMeanSquaredError: 0.5599 - val_loss: 0.3135
Epoch 20/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 323us/step - RootMeanSquaredError: 0.5379 - loss: 0.2893 - val_RootMeanSquaredError: 0.5600 - val_loss: 0.3136
Epoch 21/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - RootMeanSquaredError: 0.5339 - loss: 0.2850 - val_RootMeanSquaredError: 0.5577 - val_loss: 0.3111
Epoch 22/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - RootMeanSquaredError: 0.5310 - loss: 0.2820 - val_RootMeanSquaredError: 0.5556 - val_loss: 0.3087
Epoch 23/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 327us/step - RootMeanSquaredError: 0.5296 - loss: 0.2805 - val_RootMeanSquaredError: 0.5543 - val_loss: 0.3073
Epoch 24/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - RootMeanSquaredError: 0.5289 - loss: 0.2797 - val_RootMeanSquaredError: 0.5538 - val_loss: 0.3067
Epoch 25/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - RootMeanSquaredError: 0.5277 - loss: 0.2785 - val_RootMeanSquaredError: 0.5525 - val_loss: 0.3053
Epoch 26/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - RootMeanSquaredError: 0.5267 - loss: 0.2775 - val_RootMeanSquaredError: 0.5524 - val_loss: 0.3051
Epoch 27/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 324us/step - RootMeanSquaredError: 0.5253 - loss: 0.2760 - val_RootMeanSquaredError: 0.5508 - val_loss: 0.3034
Epoch 28/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - RootMeanSquaredError: 0.5261 - loss: 0.2768 - val_RootMeanSquaredError: 0.5514 - val_loss: 0.3040
Epoch 29/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 319us/step - RootMeanSquaredError: 0.5234 - loss: 0.2739 - val_RootMeanSquaredError: 0.5522 - val_loss: 0.3050
Epoch 30/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - RootMeanSquaredError: 0.5224 - loss: 0.2729 - val_RootMeanSquaredError: 0.5517 - val_loss: 0.3044
Epoch 31/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - RootMeanSquaredError: 0.5229 - loss: 0.2735 - val_RootMeanSquaredError: 0.5523 - val_loss: 0.3050
Epoch 32/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - RootMeanSquaredError: 0.5210 - loss: 0.2715 - val_RootMeanSquaredError: 0.5519 - val_loss: 0.3046
Epoch 33/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - RootMeanSquaredError: 0.5194 - loss: 0.2698 - val_RootMeanSquaredError: 0.5504 - val_loss: 0.3029
Epoch 34/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - RootMeanSquaredError: 0.5182 - loss: 0.2685 - val_RootMeanSquaredError: 0.5485 - val_loss: 0.3008
Epoch 35/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 324us/step - RootMeanSquaredError: 0.5175 - loss: 0.2678 - val_RootMeanSquaredError: 0.5474 - val_loss: 0.2997
Epoch 36/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - RootMeanSquaredError: 0.5185 - loss: 0.2688 - val_RootMeanSquaredError: 0.5474 - val_loss: 0.2996
Epoch 37/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 317us/step - RootMeanSquaredError: 0.5160 - loss: 0.2663 - val_RootMeanSquaredError: 0.5479 - val_loss: 0.3002
Epoch 38/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 316us/step - RootMeanSquaredError: 0.5161 - loss: 0.2664 - val_RootMeanSquaredError: 0.5492 - val_loss: 0.3016
Epoch 39/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - RootMeanSquaredError: 0.5166 - loss: 0.2668 - val_RootMeanSquaredError: 0.5479 - val_loss: 0.3002
Epoch 40/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - RootMeanSquaredError: 0.5155 - loss: 0.2657 - val_RootMeanSquaredError: 0.5471 - val_loss: 0.2993
Epoch 41/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 317us/step - RootMeanSquaredError: 0.5134 - loss: 0.2636 - val_RootMeanSquaredError: 0.5454 - val_loss: 0.2975
Epoch 42/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - RootMeanSquaredError: 0.5125 - loss: 0.2626 - val_RootMeanSquaredError: 0.5450 - val_loss: 0.2970
Epoch 43/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 359us/step - RootMeanSquaredError: 0.5122 - loss: 0.2624 - val_RootMeanSquaredError: 0.5450 - val_loss: 0.2970
Epoch 44/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - RootMeanSquaredError: 0.5134 - loss: 0.2636 - val_RootMeanSquaredError: 0.5508 - val_loss: 0.3033
Epoch 45/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - RootMeanSquaredError: 0.5169 - loss: 0.2672 - val_RootMeanSquaredError: 0.5428 - val_loss: 0.2946
Epoch 46/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 317us/step - RootMeanSquaredError: 0.5122 - loss: 0.2624 - val_RootMeanSquaredError: 0.5457 - val_loss: 0.2978
Epoch 47/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - RootMeanSquaredError: 0.5099 - loss: 0.2600 - val_RootMeanSquaredError: 0.5432 - val_loss: 0.2950
Epoch 48/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - RootMeanSquaredError: 0.5092 - loss: 0.2593 - val_RootMeanSquaredError: 0.5434 - val_loss: 0.2953
Epoch 49/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 315us/step - RootMeanSquaredError: 0.5089 - loss: 0.2589 - val_RootMeanSquaredError: 0.5431 - val_loss: 0.2949
Epoch 50/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 333us/step - RootMeanSquaredError: 0.5080 - loss: 0.2581 - val_RootMeanSquaredError: 0.5427 - val_loss: 0.2945
Epoch 51/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - RootMeanSquaredError: 0.5076 - loss: 0.2577 - val_RootMeanSquaredError: 0.5422 - val_loss: 0.2940
Epoch 52/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 368us/step - RootMeanSquaredError: 0.5080 - loss: 0.2580 - val_RootMeanSquaredError: 0.5415 - val_loss: 0.2932
Epoch 53/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - RootMeanSquaredError: 0.5091 - loss: 0.2592 - val_RootMeanSquaredError: 0.5422 - val_loss: 0.2940
Epoch 54/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - RootMeanSquaredError: 0.5080 - loss: 0.2581 - val_RootMeanSquaredError: 0.5422 - val_loss: 0.2940
Epoch 55/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 317us/step - RootMeanSquaredError: 0.5061 - loss: 0.2562 - val_RootMeanSquaredError: 0.5419 - val_loss: 0.2937
Epoch 56/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 314us/step - RootMeanSquaredError: 0.5062 - loss: 0.2562 - val_RootMeanSquaredError: 0.5416 - val_loss: 0.2933
Epoch 57/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - RootMeanSquaredError: 0.5063 - loss: 0.2564 - val_RootMeanSquaredError: 0.5409 - val_loss: 0.2925
Epoch 58/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - RootMeanSquaredError: 0.5061 - loss: 0.2561 - val_RootMeanSquaredError: 0.5406 - val_loss: 0.2923
Epoch 59/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - RootMeanSquaredError: 0.5047 - loss: 0.2547 - val_RootMeanSquaredError: 0.5402 - val_loss: 0.2918
Epoch 60/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - RootMeanSquaredError: 0.5056 - loss: 0.2557 - val_RootMeanSquaredError: 0.5399 - val_loss: 0.2914
Epoch 61/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step - RootMeanSquaredError: 0.5045 - loss: 0.2546 - val_RootMeanSquaredError: 0.5392 - val_loss: 0.2907
Epoch 62/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 323us/step - RootMeanSquaredError: 0.5045 - loss: 0.2545 - val_RootMeanSquaredError: 0.5395 - val_loss: 0.2910
Epoch 63/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - RootMeanSquaredError: 0.5041 - loss: 0.2541 - val_RootMeanSquaredError: 0.5402 - val_loss: 0.2919
Epoch 64/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 372us/step - RootMeanSquaredError: 0.5041 - loss: 0.2541 - val_RootMeanSquaredError: 0.5404 - val_loss: 0.2920
Epoch 65/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - RootMeanSquaredError: 0.5027 - loss: 0.2527 - val_RootMeanSquaredError: 0.5413 - val_loss: 0.2930
Epoch 66/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 317us/step - RootMeanSquaredError: 0.5041 - loss: 0.2541 - val_RootMeanSquaredError: 0.5414 - val_loss: 0.2931
Epoch 67/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 309us/step - RootMeanSquaredError: 0.5035 - loss: 0.2535 - val_RootMeanSquaredError: 0.5412 - val_loss: 0.2929
Epoch 68/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - RootMeanSquaredError: 0.5027 - loss: 0.2527 - val_RootMeanSquaredError: 0.5413 - val_loss: 0.2930
Epoch 69/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - RootMeanSquaredError: 0.5042 - loss: 0.2542 - val_RootMeanSquaredError: 0.5405 - val_loss: 0.2921
Epoch 70/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 314us/step - RootMeanSquaredError: 0.5012 - loss: 0.2512 - val_RootMeanSquaredError: 0.5399 - val_loss: 0.2915
Epoch 71/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 308us/step - RootMeanSquaredError: 0.5007 - loss: 0.2507 - val_RootMeanSquaredError: 0.5394 - val_loss: 0.2909
Epoch 72/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - RootMeanSquaredError: 0.5013 - loss: 0.2513 - val_RootMeanSquaredError: 0.5403 - val_loss: 0.2920
Epoch 73/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - RootMeanSquaredError: 0.5003 - loss: 0.2503 - val_RootMeanSquaredError: 0.5409 - val_loss: 0.2926
Epoch 74/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - RootMeanSquaredError: 0.5000 - loss: 0.2500 - val_RootMeanSquaredError: 0.5403 - val_loss: 0.2920
Epoch 75/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 309us/step - RootMeanSquaredError: 0.5001 - loss: 0.2501 - val_RootMeanSquaredError: 0.5407 - val_loss: 0.2924
Epoch 76/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 309us/step - RootMeanSquaredError: 0.5000 - loss: 0.2500 - val_RootMeanSquaredError: 0.5398 - val_loss: 0.2914
Epoch 77/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - RootMeanSquaredError: 0.4994 - loss: 0.2494 - val_RootMeanSquaredError: 0.5399 - val_loss: 0.2914
Epoch 78/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step - RootMeanSquaredError: 0.5043 - loss: 0.2543 - val_RootMeanSquaredError: 0.5457 - val_loss: 0.2978
Epoch 79/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - RootMeanSquaredError: 0.5062 - loss: 0.2563 - val_RootMeanSquaredError: 0.5402 - val_loss: 0.2918
Epoch 80/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 315us/step - RootMeanSquaredError: 0.4987 - loss: 0.2487 - val_RootMeanSquaredError: 0.5400 - val_loss: 0.2916
Epoch 81/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 314us/step - RootMeanSquaredError: 0.4973 - loss: 0.2473 - val_RootMeanSquaredError: 0.5386 - val_loss: 0.2901
Epoch 82/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - RootMeanSquaredError: 0.4980 - loss: 0.2480 - val_RootMeanSquaredError: 0.5402 - val_loss: 0.2918
Epoch 83/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 324us/step - RootMeanSquaredError: 0.4978 - loss: 0.2478 - val_RootMeanSquaredError: 0.5396 - val_loss: 0.2912
Epoch 84/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 314us/step - RootMeanSquaredError: 0.4975 - loss: 0.2475 - val_RootMeanSquaredError: 0.5395 - val_loss: 0.2910
Epoch 85/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - RootMeanSquaredError: 0.4976 - loss: 0.2476 - val_RootMeanSquaredError: 0.5395 - val_loss: 0.2911
Epoch 86/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - RootMeanSquaredError: 0.4974 - loss: 0.2474 - val_RootMeanSquaredError: 0.5396 - val_loss: 0.2911
Epoch 87/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - RootMeanSquaredError: 0.4966 - loss: 0.2466 - val_RootMeanSquaredError: 0.5400 - val_loss: 0.2916
Epoch 88/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - RootMeanSquaredError: 0.4969 - loss: 0.2469 - val_RootMeanSquaredError: 0.5411 - val_loss: 0.2928
Epoch 89/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 315us/step - RootMeanSquaredError: 0.4995 - loss: 0.2495 - val_RootMeanSquaredError: 0.5417 - val_loss: 0.2935
Epoch 90/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - RootMeanSquaredError: 0.4975 - loss: 0.2475 - val_RootMeanSquaredError: 0.5403 - val_loss: 0.2919
Epoch 91/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - RootMeanSquaredError: 0.4985 - loss: 0.2485 - val_RootMeanSquaredError: 0.5427 - val_loss: 0.2945
Epoch 92/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - RootMeanSquaredError: 0.4984 - loss: 0.2484 - val_RootMeanSquaredError: 0.5376 - val_loss: 0.2890
Epoch 93/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - RootMeanSquaredError: 0.4967 - loss: 0.2468 - val_RootMeanSquaredError: 0.5418 - val_loss: 0.2935
Epoch 94/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 314us/step - RootMeanSquaredError: 0.4973 - loss: 0.2473 - val_RootMeanSquaredError: 0.5391 - val_loss: 0.2906
Epoch 95/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - RootMeanSquaredError: 0.4960 - loss: 0.2460 - val_RootMeanSquaredError: 0.5408 - val_loss: 0.2925
Epoch 96/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 310us/step - RootMeanSquaredError: 0.4973 - loss: 0.2473 - val_RootMeanSquaredError: 0.5417 - val_loss: 0.2935
Epoch 97/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 310us/step - RootMeanSquaredError: 0.4957 - loss: 0.2458 - val_RootMeanSquaredError: 0.5383 - val_loss: 0.2897
Epoch 98/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - RootMeanSquaredError: 0.4945 - loss: 0.2446 - val_RootMeanSquaredError: 0.5415 - val_loss: 0.2933
Epoch 99/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - RootMeanSquaredError: 0.4943 - loss: 0.2443 - val_RootMeanSquaredError: 0.5393 - val_loss: 0.2908
Epoch 100/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 314us/step - RootMeanSquaredError: 0.4938 - loss: 0.2438 - val_RootMeanSquaredError: 0.5406 - val_loss: 0.2923
Epoch 101/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - RootMeanSquaredError: 0.4943 - loss: 0.2443 - val_RootMeanSquaredError: 0.5400 - val_loss: 0.2916
Epoch 102/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - RootMeanSquaredError: 0.4933 - loss: 0.2433 - val_RootMeanSquaredError: 0.5396 - val_loss: 0.2912
Epoch 103/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - RootMeanSquaredError: 0.4932 - loss: 0.2432 - val_RootMeanSquaredError: 0.5399 - val_loss: 0.2915
Epoch 104/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - RootMeanSquaredError: 0.4938 - loss: 0.2439 - val_RootMeanSquaredError: 0.5390 - val_loss: 0.2905
Epoch 105/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - RootMeanSquaredError: 0.4940 - loss: 0.2441 - val_RootMeanSquaredError: 0.5383 - val_loss: 0.2898
Epoch 106/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 325us/step - RootMeanSquaredError: 0.4945 - loss: 0.2446 - val_RootMeanSquaredError: 0.5400 - val_loss: 0.2916
Epoch 107/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 315us/step - RootMeanSquaredError: 0.4932 - loss: 0.2432 - val_RootMeanSquaredError: 0.5383 - val_loss: 0.2897
Epoch 108/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 319us/step - RootMeanSquaredError: 0.4931 - loss: 0.2432 - val_RootMeanSquaredError: 0.5400 - val_loss: 0.2916
Epoch 109/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 316us/step - RootMeanSquaredError: 0.4927 - loss: 0.2428 - val_RootMeanSquaredError: 0.5403 - val_loss: 0.2919
Epoch 110/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 317us/step - RootMeanSquaredError: 0.4926 - loss: 0.2427 - val_RootMeanSquaredError: 0.5391 - val_loss: 0.2906
Epoch 111/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 314us/step - RootMeanSquaredError: 0.4926 - loss: 0.2426 - val_RootMeanSquaredError: 0.5415 - val_loss: 0.2933
Epoch 112/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - RootMeanSquaredError: 0.4942 - loss: 0.2443 - val_RootMeanSquaredError: 0.5397 - val_loss: 0.2913
Epoch 113/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - RootMeanSquaredError: 0.4915 - loss: 0.2415 - val_RootMeanSquaredError: 0.5400 - val_loss: 0.2916
Epoch 114/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 329us/step - RootMeanSquaredError: 0.4922 - loss: 0.2423 - val_RootMeanSquaredError: 0.5394 - val_loss: 0.2910
Epoch 115/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 310us/step - RootMeanSquaredError: 0.4913 - loss: 0.2414 - val_RootMeanSquaredError: 0.5410 - val_loss: 0.2927
Epoch 116/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 310us/step - RootMeanSquaredError: 0.4924 - loss: 0.2425 - val_RootMeanSquaredError: 0.5403 - val_loss: 0.2920
Epoch 117/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - RootMeanSquaredError: 0.4915 - loss: 0.2416 - val_RootMeanSquaredError: 0.5398 - val_loss: 0.2914
Epoch 118/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - RootMeanSquaredError: 0.4918 - loss: 0.2418 - val_RootMeanSquaredError: 0.5357 - val_loss: 0.2870
Epoch 119/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - RootMeanSquaredError: 0.4912 - loss: 0.2413 - val_RootMeanSquaredError: 0.5352 - val_loss: 0.2865
Epoch 120/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - RootMeanSquaredError: 0.4910 - loss: 0.2411 - val_RootMeanSquaredError: 0.5376 - val_loss: 0.2890
Epoch 121/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 313us/step - RootMeanSquaredError: 0.4904 - loss: 0.2405 - val_RootMeanSquaredError: 0.5370 - val_loss: 0.2883
Epoch 122/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 311us/step - RootMeanSquaredError: 0.4906 - loss: 0.2407 - val_RootMeanSquaredError: 0.5375 - val_loss: 0.2889
Epoch 123/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 310us/step - RootMeanSquaredError: 0.4936 - loss: 0.2437 - val_RootMeanSquaredError: 0.5384 - val_loss: 0.2898
Epoch 124/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 310us/step - RootMeanSquaredError: 0.4902 - loss: 0.2403 - val_RootMeanSquaredError: 0.5383 - val_loss: 0.2897
Epoch 125/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 310us/step - RootMeanSquaredError: 0.4898 - loss: 0.2399 - val_RootMeanSquaredError: 0.5395 - val_loss: 0.2911
Epoch 126/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 312us/step - RootMeanSquaredError: 0.4897 - loss: 0.2398 - val_RootMeanSquaredError: 0.5375 - val_loss: 0.2889
Epoch 127/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - RootMeanSquaredError: 0.4890 - loss: 0.2392 - val_RootMeanSquaredError: 0.5371 - val_loss: 0.2885
Epoch 128/250
387/387 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - RootMeanSquaredError: 0.4895 - loss: 0.2396 - val_RootMeanSquaredError: 0.5376 - val_loss: 0.2890

In [22]:
mse_test = model.evaluate(X_test, y_test)
print(mse_test)

162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step - RootMeanSquaredError: 0.5237 - loss: 0.2742
[0.27421534061431885, 0.5236557722091675]

In [23]:
import pandas as pd

X_new = X_test[:3]
pd.DataFrame(X_new)

        0     1         2         3       4         5      6       7
0  1.6812  25.0  4.192201  1.022284  1392.0  3.877437  36.06 -119.01
1  2.5313  30.0  5.039384  1.193493  1565.0  2.679795  35.14 -119.46
2  3.4801  52.0  3.977155  1.185877  1310.0  1.360332  37.80 -122.44

In [24]:
y_pred = model.predict(X_new)
pd.DataFrame(y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

          0
0  0.441747
1  0.475907
2  5.086246

In [25]:
pd.DataFrame(y_test[:3])

         0
0  0.47700
1  0.45800
2  5.00001